# Generated by Django 5.0.2 on 2024-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_in_review_image', models.ImageField(blank=True, null=True, upload_to='review_image/')),
            ],
        ),
    ]
