# Generated by Django 5.0.2 on 2024-03-09 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_code', models.CharField(blank=True, default='+254', max_length=4, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('identification_number', models.CharField(max_length=50, unique=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='')),
                ('user_type', models.CharField(choices=[('student', 'student'), ('staff', 'staff')], default='student', max_length=10)),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('password', models.CharField(default='123456', max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='face_recognition_app.customuser'),
        ),
    ]
