# Generated by Django 5.0.2 on 2024-04-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0002_userinreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_image', models.ImageField(blank=True, null=True, upload_to='review_image/')),
                ('recogntion_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='userInReview',
        ),
    ]
