# Generated by Django 5.0.2 on 2024-03-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition_app.customuser'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='face_recognition_app.customuser'),
        ),
    ]
