# Generated by Django 5.0.2 on 2024-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_recognitionhistory_delete_userinreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionhistory',
            name='image_bytes',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
