# Generated by Django 5.0.2 on 2024-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0004_recognitionhistory_image_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='captured_images/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
