# Generated by Django 5.0.2 on 2024-04-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0005_alter_customuser_avatar_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
