# Generated by Django 5.0.2 on 2024-04-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0006_recognitionhistory_user_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionhistory',
            name='recogntion_time',
        ),
    ]
