# Generated by Django 5.0.2 on 2024-04-18 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0007_remove_recognitionhistory_recogntion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capturedimage',
            old_name='image',
            new_name='captured_image',
        ),
        migrations.RemoveField(
            model_name='recognitionhistory',
            name='image_bytes',
        ),
        migrations.AddField(
            model_name='recognitionhistory',
            name='recogntion_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
